name: GERemoteMic
options:
  bundleIdPrefix: com.grandelement
  deploymentTarget:
    iOS: "17.0"
targets:
  GERemoteMic:
    type: application
    platform: iOS
    sources:
      - GERemoteMic
    info:
      path: GERemoteMic/Info.plist
    entitlements:
      path: GERemoteMic/GERemoteMic.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.grandelement.GERemoteMic
        PRODUCT_NAME: GE Remote Mic
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
